import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import type { Database } from '../types/database'
import TreeNFTCard from '../components/TreeNFTCard'

type Tree    = Database['public']['Tables']['trees']['Row']
type TreeLog = Database['public']['Tables']['tree_logs']['Row'] & {
  log_type?:   string
  media_urls?: string[]
  caption?:    string
}
type SpeciesRow = { id: string; name: string; scientific_name: string | null; carbon_coeff_kg_per_cm: number | null }

const STAGE_EMOJI:  Record<string, string> = { seed: '🌰', seedling: '🌱', sapling: '🌿', tree: '🌳' }
const HEALTH_COLOR: Record<string, string> = { excellent: '#3ab87a', good: '#5a9e6f', fair: '#d97706', poor: '#ef4444' }
const HEALTH_EMOJI: Record<string, string> = { excellent: '🌟', good: '✅', fair: '⚠️', poor: '🚨' }

// ── Download helper ────────────────────────────────────────────────────────
async function fetchMediaFile(url: string): Promise<File | null> {
  try {
    const resp = await fetch(url)
    const blob = await resp.blob()
    const ext  = blob.type.includes('mp4')  ? 'mp4'
               : blob.type.includes('webm') ? 'webm'
               : blob.type.includes('jpeg') ? 'jpg'
               : 'jpg'
    return new File([blob], `mytrees_post.${ext}`, { type: blob.type })
  } catch { return null }
}

function loadImgFromUrl(url: string): Promise<HTMLImageElement | null> {
  return new Promise(res => {
    const img = new Image()
    img.onload = () => res(img)
    img.onerror = () => res(null)
    img.src = url
  })
}

async function uploadLogFile(file: File | Blob, userId: string, treeId: string, suffix: string): Promise<string | null> {
  const isBlob  = !(file instanceof File)
  const ext     = isBlob ? (file.type.includes('jpeg') ? 'jpg' : 'webm') : (file.name.split('.').pop() ?? 'jpg')
  const path    = `${userId}/${treeId}_log_${suffix}_${Date.now()}.${ext}`
  const { error } = await supabase.storage.from('tree-media').upload(path, file, { contentType: file.type || 'image/jpeg', upsert: false })
  if (error) return null
  const { data } = supabase.storage.from('tree-media').getPublicUrl(path)
  return data.publicUrl
}

// ── Planting post: single slideshow video (MP4/WebM generated by wizard) ─────
function PlantingMedia({ urls }: { urls: string[] }) {
  if (!urls.length) return (
    <div style={{ aspectRatio: '1/1', background: 'var(--bg)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 64 }}>🌱</div>
  )
  const url     = urls[0]
  const isVideo = /\.(mp4|mov|webm)/i.test(url) || url.includes('/tree-media/')
  return (
    <div style={{ aspectRatio: '1/1', background: '#000', overflow: 'hidden' }}>
      {isVideo
        ? <video src={url} controls playsInline loop style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
        : <img src={url} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
      }
    </div>
  )
}

// ── Growth post: single 1:1 composite image ──────────────────────────────
function GrowthMedia({ urls }: { urls: string[] }) {
  if (!urls.length) return null
  return (
    <div style={{ aspectRatio: '1/1', overflow: 'hidden', background: '#000' }}>
      <img src={urls[0]} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
    </div>
  )
}

// ── Composite image builder ────────────────────────────────────────────────
function loadImgEl(file: File): Promise<HTMLImageElement> {
  return new Promise(res => {
    const img = new Image()
    img.onload = () => res(img)
    img.src = URL.createObjectURL(file)
  })
}

function drawHalf(ctx: CanvasRenderingContext2D, img: HTMLImageElement, x: number, y: number, w: number, h: number) {
  const srcR = img.naturalWidth / img.naturalHeight
  const dstR = w / h
  let sx: number, sy: number, sw: number, sh: number
  if (srcR > dstR) { sh = img.naturalHeight; sw = sh * dstR; sx = (img.naturalWidth - sw) / 2; sy = 0 }
  else              { sw = img.naturalWidth;  sh = sw / dstR; sx = 0; sy = (img.naturalHeight - sh) / 2 }
  ctx.drawImage(img, sx, sy, sw, sh, x, y, w, h)
}

async function buildCompositeBlob(close: File, body: File): Promise<Blob> {
  const SIZE = 1080, HALF = SIZE / 2, GAP = 3
  const canvas = document.createElement('canvas')
  canvas.width = canvas.height = SIZE
  const ctx = canvas.getContext('2d')!
  ctx.fillStyle = '#1a1a1a'
  ctx.fillRect(0, 0, SIZE, SIZE)
  const [img1, img2, logoImg, wordmarkImg] = await Promise.all([
    loadImgEl(close), loadImgEl(body),
    loadImgFromUrl('/mytrees/logo-icon.png'),
    loadImgFromUrl('/mytrees/logo-wordmark.png'),
  ])
  drawHalf(ctx, img1, 0,              0, HALF - GAP / 2, SIZE)
  drawHalf(ctx, img2, HALF + GAP / 2, 0, HALF - GAP / 2, SIZE)
  // Watermark — logo top-left, wordmark bottom-right
  const PAD = 22, LOGO = 54
  ctx.globalAlpha = 0.82
  if (logoImg) ctx.drawImage(logoImg, PAD, PAD, LOGO, LOGO)
  if (wordmarkImg) {
    const WH = 26
    const WW = wordmarkImg.naturalWidth * (WH / wordmarkImg.naturalHeight)
    ctx.drawImage(wordmarkImg, SIZE - PAD - WW, SIZE - PAD - WH, WW, WH)
  }
  ctx.globalAlpha = 1
  return new Promise(res => canvas.toBlob(b => res(b!), 'image/jpeg', 0.92))
}

// ── Post card ─────────────────────────────────────────────────────────────
function PostCard({ log, treeName }: { log: TreeLog; treeName: string }) {
  const isPlanting  = log.log_type === 'planting'
  const urls        = log.media_urls ?? []
  const dateStr     = new Date(log.logged_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
  const [downloading, setDownloading] = useState(false)

  const handleDownload = async () => {
    if (!urls.length) return
    setDownloading(true)
    const file = await fetchMediaFile(urls[0])
    setDownloading(false)
    if (!file) return
    const a = document.createElement('a')
    a.href = URL.createObjectURL(file)
    a.download = file.name
    a.click()
    setTimeout(() => URL.revokeObjectURL(a.href), 30000)
  }

  return (
    <div style={{ background: 'var(--surface-solid)', borderRadius: 20, overflow: 'hidden', boxShadow: 'var(--neu-shadow)', border: '1px solid rgba(212,219,229,0.4)' }}>

      {/* Post header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '12px 14px 10px' }}>
        <div style={{
          width: 38, height: 38, borderRadius: '50%', flexShrink: 0,
          background: isPlanting ? 'linear-gradient(135deg,#0a2a1a,#3ab87a)' : 'var(--bg)',
          boxShadow: 'var(--neu-inset-sm)',
          display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20,
        }}>
          {isPlanting ? '🌱' : STAGE_EMOJI[log.health] ?? '🌿'}
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <p style={{ fontSize: 14, fontWeight: 700, color: 'var(--color-fg)', margin: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
            {treeName}
          </p>
          <p style={{ fontSize: 11, color: 'var(--color-tertiary)', margin: 0 }}>
            {isPlanting ? '🌱 Planting day' : `📏 Growth check · ${dateStr}`}
          </p>
        </div>
        {/* Download button */}
        {urls.length > 0 && (
          <button onClick={handleDownload} disabled={downloading} style={{
            display: 'flex', alignItems: 'center', gap: 4, padding: '6px 12px',
            borderRadius: 20, border: '1px solid var(--border)',
            background: 'var(--bg)', cursor: downloading ? 'wait' : 'pointer', fontFamily: 'inherit',
            opacity: downloading ? 0.6 : 1,
          }}>
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{ color: 'var(--color-secondary)' }}>
              <path d="M12 3v13M5 16l7 7 7-7"/><path d="M3 21h18"/>
            </svg>
            <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--color-secondary)' }}>
              {downloading ? '…' : 'Save'}
            </span>
          </button>
        )}
      </div>

      {/* Media */}
      {urls.length > 0 && (
        isPlanting
          ? <PlantingMedia urls={urls} />
          : <GrowthMedia urls={urls} />
      )}
      {urls.length === 0 && !isPlanting && (
        <div style={{ margin: '0 14px', borderRadius: 12, background: 'var(--bg)', padding: '12px 14px', display: 'flex', alignItems: 'center', gap: 10 }}>
          <span style={{ fontSize: 28 }}>{STAGE_EMOJI['seedling']}</span>
          <p style={{ fontSize: 12, color: 'var(--color-tertiary)', margin: 0 }}>No photos for this entry</p>
        </div>
      )}

      {/* Caption / stats */}
      <div style={{ padding: '12px 14px 14px' }}>
        {log.caption && (
          <p style={{ fontSize: 14, color: 'var(--color-fg)', lineHeight: 1.55, marginBottom: 10 }}>
            {log.caption}
          </p>
        )}

        {/* Stats row */}
        {!isPlanting && (log.height_cm || log.canopy_cm || log.health) && (
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 0 }}>
            {log.health && (
              <span style={{ fontSize: 11, fontWeight: 700, color: HEALTH_COLOR[log.health], background: `${HEALTH_COLOR[log.health]}18`, borderRadius: 8, padding: '3px 9px' }}>
                {HEALTH_EMOJI[log.health]} {log.health}
              </span>
            )}
            {log.height_cm && (
              <span style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-secondary)', background: 'var(--bg)', borderRadius: 8, padding: '3px 9px' }}>
                📏 {log.height_cm} cm tall
              </span>
            )}
            {log.canopy_cm && (
              <span style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-secondary)', background: 'var(--bg)', borderRadius: 8, padding: '3px 9px' }}>
                🌿 {log.canopy_cm} cm canopy
              </span>
            )}
          </div>
        )}
        {/* Date on planting post */}
        {isPlanting && (
          <p style={{ fontSize: 11, color: 'var(--color-tertiary)', margin: 0 }}>🗓 {dateStr}</p>
        )}
      </div>
    </div>
  )
}

// ── Log form ──────────────────────────────────────────────────────────────
function LogForm({ treeId, userId, onSaved }: { treeId: string; userId: string; onSaved: (log: TreeLog) => void }) {
  const [form, setForm] = useState({ height_cm: '', canopy_cm: '', health: 'good' as TreeLog['health'], caption: '' })
  const captionWords  = form.caption.trim().split(/\s+/).filter(Boolean).length
  const captionOk     = captionWords >= 15 && captionWords <= 45
  const [closeFile,   setCloseFile]   = useState<File | null>(null)
  const [closePreview, setClosePreview] = useState<string | null>(null)
  const [bodyFile,    setBodyFile]    = useState<File | null>(null)
  const [bodyPreview, setBodyPreview] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const [error,  setError]  = useState<string | null>(null)

  const pickFile = (e: React.ChangeEvent<HTMLInputElement>, which: 'close' | 'body') => {
    const f = e.target.files?.[0]; if (!f) return
    const url = URL.createObjectURL(f)
    if (which === 'close') { setCloseFile(f); setClosePreview(url) }
    else                   { setBodyFile(f);  setBodyPreview(url)  }
  }

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!closeFile)  { setError('Close-up photo is required'); return }
    if (!bodyFile)   { setError('Full-body photo is required'); return }
    if (!captionOk)  { setError('Caption must be 15–45 words'); return }
    setSaving(true); setError(null)
    // Composite the two photos into one 1:1 image
    const compositeBlob = await buildCompositeBlob(closeFile, bodyFile)
    const compositeUrl  = await uploadLogFile(compositeBlob as unknown as File, userId, treeId, 'composite')
    const mediaUrls = compositeUrl ? [compositeUrl] : []
    const { data: log } = await supabase.from('tree_logs').insert({
      tree_id: treeId, log_type: 'growth',
      height_cm: form.height_cm ? parseFloat(form.height_cm) : null,
      canopy_cm: form.canopy_cm ? parseFloat(form.canopy_cm) : null,
      health: form.health,
      notes: null,
      caption: form.caption || null,
      media_urls: mediaUrls,
      xp_awarded: 30,
    }).select('*').single()
    try { await supabase.rpc('award_xp', { user_id: userId, amount: 30 }) } catch { /**/ }
    setSaving(false)
    if (log) onSaved(log as TreeLog)
  }

  const PhotoPick = ({ which, file, preview, label }: { which: 'close' | 'body'; file: File | null; preview: string | null; label: string }) => (
    <div>
      <p style={{ fontSize: 11, fontWeight: 700, color: 'var(--color-secondary)', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6 }}>{label} <span style={{ color: '#ef4444' }}>*</span></p>
      <label style={{
        display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
        border: `2px ${file ? 'solid' : 'dashed'} ${file ? 'rgba(58,184,122,0.4)' : 'var(--border)'}`,
        borderRadius: 12, cursor: 'pointer', background: 'var(--bg)',
        overflow: 'hidden', aspectRatio: '1/1', minHeight: 100,
      }}>
        <input type="file" accept="image/*" capture="environment" style={{ display: 'none' }} onChange={e => pickFile(e, which)} />
        {preview
          ? <img src={preview} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
          : <><span style={{ fontSize: 28, marginBottom: 4 }}>📷</span><span style={{ fontSize: 11, color: 'var(--color-tertiary)', fontWeight: 600 }}>Tap to shoot</span></>
        }
      </label>
    </div>
  )

  return (
    <div className="card" style={{ padding: 20, marginBottom: 20 }}>
      <h3 className="section-title" style={{ marginBottom: 16 }}>Today's check-in · +30 XP</h3>
      <form onSubmit={handleSave}>
        {/* Required photos */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 16 }}>
          <PhotoPick which="close" file={closeFile} preview={closePreview} label="Close-up of plant" />
          <PhotoPick which="body"  file={bodyFile}  preview={bodyPreview}  label="You next to it"  />
        </div>

        {/* Measurements */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 14 }}>
          <div>
            <label className="label">Height (cm)</label>
            <input className="input" type="number" value={form.height_cm} onChange={e => setForm(f => ({ ...f, height_cm: e.target.value }))} step="any" placeholder="45" />
          </div>
          <div>
            <label className="label">Canopy (cm)</label>
            <input className="input" type="number" value={form.canopy_cm} onChange={e => setForm(f => ({ ...f, canopy_cm: e.target.value }))} step="any" placeholder="20" />
          </div>
        </div>

        <div style={{ marginBottom: 14 }}>
          <label className="label">Health</label>
          <select className="input" value={form.health} onChange={e => setForm(f => ({ ...f, health: e.target.value as TreeLog['health'] }))}>
            <option value="excellent">Excellent 🌟</option>
            <option value="good">Good ✅</option>
            <option value="fair">Fair ⚠️</option>
            <option value="poor">Poor 🚨</option>
          </select>
        </div>

        <div style={{ marginBottom: 18 }}>
          <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 4 }}>
            <label className="label">Caption <span style={{ color: '#ef4444' }}>*</span></label>
            <span style={{
              fontSize: 11, fontWeight: 600,
              color: captionWords === 0 ? 'var(--color-tertiary)'
                   : captionOk          ? 'var(--accent)'
                   : captionWords > 45  ? '#ef4444'
                   : 'var(--color-tertiary)',
            }}>
              {captionWords} / 15–45 words
            </span>
          </div>
          <textarea
            className="input"
            value={form.caption}
            onChange={e => setForm(f => ({ ...f, caption: e.target.value }))}
            placeholder="How is it looking today? Describe the growth, the spot, and how you're feeling about it… (15–45 words)"
            rows={3}
            style={{ resize: 'none', borderColor: captionWords > 0 && !captionOk ? '#ef4444' : undefined }}
          />
        </div>

        {error && <p style={{ fontSize: 12, color: '#ef4444', marginBottom: 12 }}>{error}</p>}

        <button type="submit" className="btn-primary" disabled={saving || !captionOk}>
          {saving ? 'Saving…' : '📏 Save log · +30 XP'}
        </button>
      </form>
    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────
export default function TreeDetail() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const [tree,     setTree]     = useState<Tree | null>(null)
  const [species,  setSpecies]  = useState<SpeciesRow | null>(null)
  const [logs,     setLogs]     = useState<TreeLog[]>([])
  const [showLog,  setShowLog]  = useState(false)
  const [showCard, setShowCard] = useState(false)
  const [userId,   setUserId]   = useState<string | null>(null)

  useEffect(() => {
    if (!id) return
    supabase.auth.getUser().then(({ data: { user } }) => { if (user) setUserId(user.id) })
    Promise.all([
      supabase.from('trees').select('*').eq('id', id).single(),
      supabase.from('tree_logs').select('*').eq('tree_id', id).order('logged_at', { ascending: false }),
    ]).then(async ([{ data: t }, { data: l }]) => {
      setTree(t); setLogs((l as TreeLog[]) ?? [])
      if (t?.species_id) {
        const { data: sp } = await supabase.from('species').select('id,name,scientific_name,carbon_coeff_kg_per_cm').eq('id', t.species_id).single()
        setSpecies(sp)
      }
    })
  }, [id])

  const handleLogSaved = (log: TreeLog) => {
    setLogs(prev => [log, ...prev])
    setShowLog(false)
  }

  if (!tree) return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 260 }}>
      <div style={{ fontSize: 40 }} className="animate-bounce">🌱</div>
    </div>
  )

  return (
    <div>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 24 }}>
        <button className="btn-back" onClick={() => navigate(-1)}>←</button>
        <div>
          <p className="page-eyebrow">{STAGE_EMOJI[tree.stage]} {tree.stage}</p>
          <h1 className="page-title" style={{ fontSize: 24 }}>{tree.name}</h1>
        </div>
      </div>

      {/* Info card */}
      <div className="card" style={{ padding: 18, marginBottom: 16 }}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px 20px' }}>
          <div><p className="label" style={{ marginBottom: 2 }}>Stage</p><p style={{ fontSize: 15, fontWeight: 500, color: 'var(--color-fg)', textTransform: 'capitalize' }}>{tree.stage}</p></div>
          <div><p className="label" style={{ marginBottom: 2 }}>Planted</p><p style={{ fontSize: 15, fontWeight: 500, color: 'var(--color-fg)' }}>{tree.planted_at ? new Date(tree.planted_at).toLocaleDateString() : '—'}</p></div>
          {species && <div style={{ gridColumn: '1/-1' }}><p className="label" style={{ marginBottom: 2 }}>Species</p><p style={{ fontSize: 13, color: 'var(--color-secondary)' }}>{species.name} · <em>{species.scientific_name}</em></p></div>}
        </div>
      </div>

      {/* Action buttons */}
      <button className="btn-primary" onClick={() => setShowCard(true)} style={{ marginBottom: 10, background: 'linear-gradient(135deg,#1e003c,#7c3aed)', border: 'none' }}>
        ✨ View NFT Card
      </button>
      <button className="btn-primary" onClick={() => setShowLog(v => !v)} style={{ marginBottom: 24 }}>
        📏 Log growth today · +30 XP
      </button>

      {/* NFT modal */}
      {showCard && (
        <div onClick={() => setShowCard(false)} style={{ position: 'fixed', inset: 0, zIndex: 1000, background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(8px)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: 24 }}>
          <div onClick={e => e.stopPropagation()}>
            <TreeNFTCard treeId={tree.id} treeName={tree.name} stage={tree.stage} plantedAt={tree.planted_at}
              speciesName={species ? `${species.name} · ${species.scientific_name}` : null}
              carbonCoeff={species?.carbon_coeff_kg_per_cm ?? null}
              heightCm={logs.find(l => l.height_cm)?.height_cm ?? null} />
          </div>
          <p style={{ marginTop: 20, fontSize: 12, color: 'rgba(255,255,255,0.4)', textAlign: 'center' }}>Tap outside to close</p>
        </div>
      )}

      {/* Log form */}
      {showLog && userId && <LogForm treeId={tree.id} userId={userId} onSaved={handleLogSaved} />}

      {/* Post feed */}
      <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 16 }}>
        <h2 className="section-title">Growth history</h2>
        <p className="section-subtitle">{logs.length} posts</p>
      </div>

      {logs.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '32px 0', color: 'var(--color-tertiary)', fontSize: 14 }}>
          <div style={{ fontSize: 40, marginBottom: 10 }}>📷</div>
          No posts yet — log your first update!
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16, paddingBottom: 8 }}>
          {logs.map(log => (
            <PostCard key={log.id} log={log} treeName={tree.name} />
          ))}
        </div>
      )}

    </div>
  )
}
